### ISSUE TITLE
Placeholder: %server_uptime% brings up an internal error & is listed incorrectly

### ISSUE THREAD

**Issue by Zefferis** [PlaceholderAPI/Server-Expansion#14]
Issue:

Parsing the previously working placeholder for the Server Expansion "**%server_uptime%**" produces an error in the server log:

```[09:56:06] [Server thread/INFO]: Zefferis issued server command: /papi parse me %server_uptime%
[09:56:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.10.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-126]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-126]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-126]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-126]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPIPlugin.getUptime()Ljava/lang/String;
	at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:130) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:180) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:77) ~[?:?]
	at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:122) ~[?:?]
	at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:62) ~[?:?]
	at me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:115) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-126]
	... 18 more
```

This is produced using the latest 2.2.3 Server Expansion with the Latest PAPI (2.10.7)

Also on the ecloud website the expansion seems to be mistakenly written as %server_up%% rather than %server_uptime%

This mistype appears both on the website and in-game; but not within the PlaceholderAPI Wiki

**Comment by extendedclip** [comment]
Adding on to this since it has been re implemented, the current method does not get the correct start time. Server started just a few mins ago.. https://img.extendedclip.com/chrome_2020-07-31_21-48-58.png

**Comment by MrEDok** [comment]
> Adding on to this since it has been re implemented, the current method does not get the correct start time. Server started just a few mins ago.. https://img.extendedclip.com/chrome_2020-07-31_21-48-58.png

doing /papi parse me %server_uptime%
https://pastebin.com/L094pZiL
on Papi 2.10.8

**Comment by MrGraycat** [comment]
> 
> doing /papi parse me %server_uptime%
> https://pastebin.com/L094pZiL
> on Papi 2.10.8

Update the server expansion it still uses the old code.

> 
> 
> Adding on to this since it has been re implemented, the current method does not get the correct start time. Server started just a few mins ago.. https://img.extendedclip.com/chrome_2020-07-31_21-48-58.png

check #15 which will fix this issue :)

**Comment by darbyjack** [comment]
Should be fixed via https://github.com/PlaceholderAPI/Server-Expansion/commit/5bb45758c1f4df08733a64f05c865d30b48809ec. Please re-open if you continue to experience problems.
