### ISSUE TITLE
Unable to use Server expansion with Purpur: Asynchronous Chunk getEntities call

### ISSUE THREAD

**Issue by rrunswickjr** [PlaceholderAPI/Server-Expansion#30]
Server: This server is running Purpur version git-Purpur-1236 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: c0244ec on HEAD)

PI Version: PlaceholderAPI (2.10.9)

Stack Trace:
[pool-42-thread-2/FATAL]: Thread pool-42-thread-2 failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Purpur-1236]
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2368) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1172) ~[patched_1.17.jar:git-Purpur-1236]
	at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:190) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
	at me.neznamy.tab.platforms.bukkit.BukkitPlatform.setPlaceholders(BukkitPlatform.java:245) ~[?:?]
	at me.neznamy.tab.platforms.bukkit.BukkitPlatform$2.get(BukkitPlatform.java:210) ~[?:?]
	at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:36) ~[?:?]
	at me.neznamy.tab.shared.features.PlaceholderManager.updatePlayerPlaceholder(PlaceholderManager.java:119) ~[?:?]
	at me.neznamy.tab.shared.features.PlaceholderManager.access$200(PlaceholderManager.java:35) ~[?:?]
	at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:83) ~[?:?]
	at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:166) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by darbyjack** [comment]
We don't call it async. Most likely your tab plugin.

**Comment by rrunswickjr** [comment]
I do call the placeholder within Tab, but the error only goes away when I unload the Server expansion in papi.  So, Uncertain what Tab is specifically doing with this, but I guess I will report to them.  Thanks.

**Comment by darbyjack** [comment]
Most likely calling their placeholders async.

**Comment by rrunswickjr** [comment]
I appreciate the quick info!
