### ISSUE TITLE
1.17.1 update?

### ISSUE THREAD

**Issue by leasoncre** [PlaceholderAPI/Server-Expansion#31]
expansion errors on new 1.17.1 MC
```[20:52:32] [pool-22-thread-2/FATAL]: Thread pool-22-thread-2 failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Airplane-43]
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2366) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1172) ~[patched_1.17.1.jar:git-Airplane-43]
	at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:190) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
	at me.neznamy.tab.platforms.bukkit.BukkitPlatform.setPlaceholders(BukkitPlatform.java:245) ~[?:?]
	at me.neznamy.tab.platforms.bukkit.BukkitPlatform$2.get(BukkitPlatform.java:210) ~[?:?]
	at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:36) ~[?:?]
	at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.getLastValue(PlayerPlaceholder.java:59) ~[?:?]
	at me.neznamy.tab.shared.placeholders.Placeholder.set(Placeholder.java:96) ~[?:?]
	at me.neznamy.tab.shared.Property.update(Property.java:154) ~[?:?]
	at me.neznamy.tab.shared.Property.updateAndGet(Property.java:141) ~[?:?]
	at me.neznamy.tab.shared.features.HeaderFooter.refresh(HeaderFooter.java:95) ~[?:?]
	at me.neznamy.tab.shared.features.PlaceholderManager.refresh(PlaceholderManager.java:181) ~[?:?]
	at me.neznamy.tab.shared.features.PlaceholderManager.access$400(PlaceholderManager.java:35) ~[?:?]
	at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:86) ~[?:?]
	at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:166) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by darbyjack** [comment]
Tab is calling something async that it probably shouldn't.

**Comment by leasoncre** [comment]
> Tab is calling something async that it probably shouldn't.

previously i updated serverexpantion when i fired up my 1.17.0 dev server (previously ran it on 1.16.5 over 2 months ago) and it resolved the issue. haven't done anything to TAB

I'll post/ask neznamy too

**Comment by darbyjack** [comment]
As I said, they are doing something async and spigot isn't liking it.

**Comment by leasoncre** [comment]
-closed, issue was ASYNC call on entity count placeholders
fixed by forcing sync process on those calls within TAB config
%sync:server_total_living_entities% | %sync:server_total_entities%

**Comment by darbyjack** [comment]
Nice
