### ISSUE TITLE
%server_total_living_entities% and %server_total_entities% broken

### ISSUE THREAD

**Issue by qbasty** [PlaceholderAPI/Server-Expansion#32]
https://paste.helpch.at/fayozidove

im using the 2 placeholders in my tab
here is the error that is spamming the console:
`[22:16:25 FATAL]: Thread pool-25-thread-2 failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2360) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1173) ~[patched_1.17.1.jar:git-Purpur-1287]
        at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:190) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.BukkitPlatform.setPlaceholders(BukkitPlatform.java:240) ~[?:?]
        at me.neznamy.tab.platforms.bukkit.BukkitPlatform$2.get(BukkitPlatform.java:205) ~[?:?]
        at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:36) ~[?:?]
        at me.neznamy.tab.shared.features.PlaceholderManager.updatePlayerPlaceholder(PlaceholderManager.java:116) ~[?:?]
        at me.neznamy.tab.shared.features.PlaceholderManager.lambda$new$0(PlaceholderManager.java:81) ~[?:?]
        at me.neznamy.tab.shared.cpu.CPUManager.lambda$startRepeatingMeasuredTask$2(CPUManager.java:146) ~[?:?]
        at me.neznamy.tab.shared.cpu.CPUManager.lambda$submit$4(CPUManager.java:180) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutorPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

`PlaceholderAPI: 2.10.9

Expansions Registered:
  spark      [Author: Luck, Version: 1.6.0]
  tab        [Author: [NEZNAMY], Version: 2.9.2]
  player     [Author: clip, Version: 2.0.0]
  server     [Author: clip, Version: 2.6.0]
  worldstats [Author: moo, Version: 1.7]

Expansions Directory:
  Expansion-player.jar
  Expansion-server.jar

Server Info: 1.17.1-R0.1-SNAPSHOT/git-Purpur-1287 (MC: 1.17.1)

Plugin Info:
  Chunky           [Version: 1.2.86]
  ChunkyBorder     [Version: 1.0.38]
  CommandWhitelist [Version: 1.7.8]
  FarmControl      [Version: 1.1.8]
  JoinLeave        [Version: 1.0-SNAPSHOT]
  PistonChat       [Version: 1.5.1]
  PlaceholderAPI   [Version: 2.10.9]
  TAB              [Version: 2.9.2]
  Worldstats       [Version: 1.7]
  spark            [Version: 1.6.0]`

**Comment by darbyjack** [comment]
Force tab to run the placeholder sync.
