### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer

### ISSUE THREAD

**Issue by MarvinKlar** [PlaceholderAPI/Server-Expansion#41]
For some reason I am getting this error on my latest Paper 1.17.1 server using PlaceholderAPI v2.11.1:
```
[13:02:23] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer
[13:02:23] [Server thread/WARN]: 	at java.base/java.lang.Class.forNameImpl(Native Method)
[13:02:23] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:350)
[13:02:23] [Server thread/WARN]: 	at com.extendedclip.papi.expansion.server.ServerExpansion.<init>(ServerExpansion.java:61)
[13:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[13:02:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:02:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:02:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[13:02:23] [Server thread/WARN]: 	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.createExpansionInstance(LocalExpansionManager.java:422)
[13:02:23] [Server thread/WARN]: 	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:162)
[13:02:23] [Server thread/WARN]: 	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager$$Lambda$7432/0x00000000f7248628.apply(Unknown Source)
[13:02:23] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[13:02:23] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[13:02:23] [Server thread/WARN]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[13:02:23] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
[13:02:23] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[13:02:23] [Server thread/WARN]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[13:02:23] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[13:02:23] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[13:02:23] [Server thread/WARN]: 	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$registerAll$4(LocalExpansionManager.java:333)
[13:02:23] [Server thread/WARN]: 	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager$$Lambda$7218/0x00000000f7247438.accept(Unknown Source)
[13:02:23] [Server thread/WARN]: 	at me.clip.placeholderapi.util.Futures.lambda$onMainThread$0(Futures.java:46)
[13:02:23] [Server thread/WARN]: 	at me.clip.placeholderapi.util.Futures$$Lambda$7430/0x00000000f7248130.run(Unknown Source)
[13:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[13:02:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[13:02:23] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[13:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[13:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[13:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:02:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer$$Lambda$3652/0x00000000be7fedd8.run(Unknown Source)
[13:02:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:853)
[13:02:23] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server [2.2.3]
```

Should I worry about that?

**Comment by Kqliber** [comment]
Please update the server expansion. The latest version is 2.6.0 and should fix this issue.

**Comment by MarvinKlar** [comment]
I just noticed that I had an extension called `Expansion-server.jar` and one called `Expansion-Server.jar` installed. I removed the older one (which had the old version), restarted and everythink works fine!
