### ISSUE TITLE
Failed to load class files of expansion

### ISSUE THREAD

**Issue by SlimeDog** [PlaceholderAPI/Server-Expansion#49]
Paper 1.19.3-431 (and previous for quite some time)

```
> version PlaceholderAPI
[11:14:45 INFO]: PlaceholderAPI version 2.11.3-DEV-165
> papi list
[11:15:16 INFO]: A total of 20 placeholder hook(s) are active: 
atr, bentobox, biomeremap, bskyblock, citizensplaceholder, cmil, combatlogx, coordinatetool, deluxemenus, extrahardmode
frp, level, plan, pyroweatherpro, residence, server, spark, stat, treefeller, wesv
> papi ecloud list installed
[11:15:33 INFO]: Installed Expansions
    Name            Author  Verified  Version  
-----------------------------------------------
1.  CoordinateTool  vk2gpz  Y         3.5.3    
2.  Server          clip    Y         2.6.1 
```
Note that only Server is a PAPI expansion; CoordinateTool is provided by the plugin itself, as are the other active hooks.

On server startup
```
[11:10:03] [Server thread/INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.3-DEV-165
[11:10:04] [Server thread/INFO]: [CombatLogX] Loading expansion 'PlaceholderAPI Compatibility v16.9'...
[11:10:24] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.3-DEV-165
[11:10:25] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: citizensplaceholder [1.0.0]
[11:10:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: cmil [1.2.4.5]
[11:10:35] [Server thread/INFO]: PlaceholderAPI hooked.
[11:10:37] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: insights [6.14.1-SNAPSHOT]
[11:10:37] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: residence [5.1.1.1]
[11:10:37] [Server thread/INFO]: [Residence] PlaceholderAPI was found - Enabling capabilities.
[11:10:44] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: extrahardmode [3.15.0-4fadc2b]
[11:10:44] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: frp [1.11.34 (build 615)]
[11:10:45] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: ocm [2.0.0BETA]
[11:10:45] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: Telecom [1.0.0-beta0.25]
[11:10:45] [Server thread/INFO]: [HelpGUI] Checking for PlaceholderAPI...
[11:10:45] [Server thread/INFO]: [HelpGUI] Hooked into PlaceholderAPI.
[11:10:47] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: wesv [2.1.3]
[11:10:47] [Server thread/INFO]: [WESV] PlaceholderAPI extension successfully registered.
[11:10:47] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: treefeller [1.0.0]
[11:10:47] [Server thread/INFO]: [StatisticEditor] PlaceholderAPI found, registering hook
[11:10:47] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: stat [1.6.1]
[11:10:48] [Server thread/INFO]: [Server Tutorial Plus] PlaceholderAPI has been found!
[11:10:48] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: PyroWeatherPro [4.3.0]
[11:10:49] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: coordinatetool [3.5.3]
[11:10:49] [Server thread/INFO]: [TabList] Hooked PlaceholderAPI version: 2.11.3-DEV-165
[11:10:51] [Server thread/INFO]: [Plan] Registered extension: PlaceholderAPI
[11:11:02] [Server thread/INFO]: [DeluxeMenus] Successfully hooked into PlaceholderAPI!
[11:11:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: deluxemenus [1.13.7-DEV-156]
[11:11:03] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: atr [10.6]
[11:11:04] [Server thread/INFO]: [MobHunting] Enabling compatibility with PlaceholderAPI (2.11.3-DEV-165).
[11:11:04] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: mobhunting [1.0.0]
[11:11:05] [Server thread/INFO]: [CombatLogX] Enabling expansion 'PlaceholderAPI Compatibility v16.9'...
[11:11:05] [Server thread/INFO]: [CombatLogX] [PlaceholderAPI Compatibility] Successfully found a dependency: PlaceholderAPI v2.11.3-DEV-165
[11:11:05] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: combatlogx [16.9]
[11:11:06] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: spark [1.10.29]
[11:11:06] [Server thread/INFO]: [spark] Registered PlaceholderAPI placeholders
[11:11:06] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: biomeremap [3.1.0]
[11:11:07] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[11:11:07] [Server thread/INFO]: [BentoBox] Hooking with PlaceholderAPI...
[11:11:07] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bentobox [1.22.1-SNAPSHOT-b2366]
[11:11:07] [Craft Scheduler Thread - 8 - ItemJoin/INFO]: [ItemJoin] Hooked into { Multiverse-Core, Multiverse-Inventories, WorldGuard, PlaceholderAPI, ProtocolLib, Citizens, Vault }
[11:11:08] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: level [2.10.0-SNAPSHOT-b528]
[11:11:09] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bskyblock [1.17.0-SNAPSHOT-b730]
[11:11:10] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: plan [5.5 build 2254]
[11:11:24] [Server thread/ERROR]: [PlaceholderAPI] Failed to load class files of expansion.
java.util.concurrent.CompletionException: java.lang.IllegalStateException: zip file closed
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:428) ~[PlaceholderAPI-2.11.3-b165.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:832) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:193) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:128) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:34) ~[paper-1.19.3.jar:git-Paper-431]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.19.3.jar:git-Paper-431]
        at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.19.3.jar:git-Paper-431]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:171) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:148) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:575) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:62) ~[PlaceholderAPI-2.11.3-b165.jar:?]
        at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:405) ~[PlaceholderAPI-2.11.3-b165.jar:?]
        ... 7 more
[11:11:25] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[11:11:25] [Server thread/INFO]: AcceptTheRules, BiomeRemap, Chunky, ChunkyBorder, Citizens, CommandSigns, ConsoleSpamFix, DeluxeMenus, Essentials, EssentialsChat, EssentialsGeoIP, ExtraContexts, ForceResourcepacks, ItemJoin, LuckPerms, MobColors, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, NetworkInterceptor, pHD, PlaceholderAPI, PluginVersions, ProtocolLib, ServerListPlus, Shopkeepers, Skript, spark, TabList, Vault, VoidSpawn, WorldEdit, WorldGuard
[11:11:42] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server [2.6.1]
[11:14:45] [Server thread/INFO]: PlaceholderAPI version 2.11.3-DEV-165
```

**Comment by SlimeDog** [comment]
Looks to be fixed in PAPI-Expansion-Server 2.6.2. Thanks.
