### ISSUE TITLE
Failed to remap class at.helpch.placeholderapi.expansion.server.ServerExpansion

### ISSUE THREAD

**Issue by KanyShigure** [PlaceholderAPI/Server-Expansion#58]
[18:04:24 ERROR]: [PlaceholderAPI] Failed to load class files of expansion.
 java.util.concurrent.CompletionException: Failed to remap class at.helpch.placeholderapi.expansion.server.ServerExpansion (expansion file: D:\server\plugins\PlaceholderAPI\expansions\PAPI-Expansion-Server-2.7.2.jar)
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:443) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1604) ~[?:1.8.0_352]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:1.8.0_352]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[?:1.8.0_352]
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289) ~[?:1.8.0_352]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[?:1.8.0_352]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_352]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_352]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_352]
Caused by: java.lang.ClassNotFoundException: Failed to remap class at.helpch.placeholderapi.expansion.server.ServerExpansion
	at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.remappedFindClass(DelegateURLClassLoder.java:109) ~[DelegateURLClassLoder.class:?]
	at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.findClass(DelegateURLClassLoder.java:65) ~[DelegateURLClassLoder.class:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_352]
	at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:62) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:421) ~[?:?]
	... 8 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
	at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:154) ~[MohistJarRemapper.class:?]
	at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.remappedFindClass(DelegateURLClassLoder.java:93) ~[DelegateURLClassLoder.class:?]
	at com.mohistmc.bukkit.nms.proxy.DelegateURLClassLoder.findClass(DelegateURLClassLoder.java:65) ~[DelegateURLClassLoder.class:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_352]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_352]
	at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:62) ~[?:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:421) ~[?:?]
	... 8 more

**Comment by iGabyTM** [comment]
@KanyShigure if the plugin happens to work on modded servers, that's great, but we don't support it.
