### ISSUE TITLE
%server_countdown_<SimpleDateFormat>_<time>% not working

### ISSUE THREAD

**Issue by JorisvD01** [PlaceholderAPI/Server-Expansion#62]
Hey, after using this placeholder it keeps showing "invalid time" and spamming this error in de console;

```
[14:18:02 ERROR]: [PlaceholderAPI] [server] Could not calculate countdown (format: "Value(YearOfEra,4,19,EXCEEDS_PAD)Value(MonthOfYear,2)Value(DayOfMonth,2)", other date: "20240912")
java.time.format.DateTimeParseException: Text '20240912' could not be parsed: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO resolved to 2024-09-12 of type java.time.format.Parsed
at java.base/java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:2079) ~[?:?]
at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2014) ~[?:?]
at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:494) ~[?:?]
at at.helpch.placeholderapi.expansion.server.util.TimeFormatter.calculateTimeBetween(TimeFormatter.java:142) ~[?:?]
at at.helpch.placeholderapi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:239) ~[?:?]
at PlaceholderAPI-2.11.6 (2).jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6 (2).jar:?]
at PlaceholderAPI-2.11.6 (2).jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6 (2).jar:?]
at PlaceholderAPI-2.11.6 (2).jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6 (2).jar:?]
at TAB v4.1.6 (2).jar/me.neznamy.tab.platforms.bukkit.platform.BukkitPlatform.lambda$registerUnknownPlaceholder$6(BukkitPlatform.java:191) ~[TAB v4.1.6 (2).jar:?]
at TAB v4.1.6 (2).jar/me.neznamy.tab.shared.placeholders.types.ServerPlaceholderImpl.request(ServerPlaceholderImpl.java:107) ~[TAB v4.1.6 (2).jar:?]
at TAB v4.1.6 (2).jar/me.neznamy.tab.shared.placeholders.PlaceholderRefreshTask.run(PlaceholderRefreshTask.java:49) ~[TAB v4.1.6 (2).jar:?]
at TAB v4.1.6 (2).jar/me.neznamy.tab.shared.features.PlaceholderManagerImpl.lambda$refresh$1(PlaceholderManagerImpl.java:84) ~[TAB v4.1.6 (2).jar:?]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.time.DateTimeException: Unable to obtain LocalDateTime from TemporalAccessor: {},ISO resolved to 2024-09-12 of type java.time.format.Parsed
at java.base/java.time.LocalDateTime.from(LocalDateTime.java:463) ~[?:?]
at java.base/java.time.format.Parsed.query(Parsed.java:247) ~[?:?]
at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2010) ~[?:?]
... 16 more
Caused by: java.time.DateTimeException: Unable to obtain LocalTime from TemporalAccessor: {},ISO resolved to 2024-09-12 of type java.time.format.Parsed
at java.base/java.time.LocalTime.from(LocalTime.java:441) ~[?:?]
at java.base/java.time.LocalDateTime.from(LocalDateTime.java:459) ~[?:?]
at java.base/java.time.format.Parsed.query(Parsed.java:247) ~[?:?]
at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:2010) ~[?:?]
... 16 more
```

Exact placeholder used: %server_countdown_yyyy.MM.dd_2024.09.04%

Server version: Paper version 1.21-99-master@f1f01a1
PlaceholderAPI version: 2.11.6

**Comment by samhtm** [comment]
Managed to fix this issue by doing two things:

1. Revert to the previous version of the server expansion (/papi ecloud download Server 2.7.1)
2. Add a time to the placeholder (in your case %server_countdown_yyyy.MM.dd HH:mm:ss_2024.09.04 00:00:00%) which will return midnight at the specified time on that date (change accordingly of course)

**Comment by iGabyTM** [comment]
We've changed the API used for countdown, from Date to LocalDateTime to allow you to set the time zone (e.g. UTC+3) and the local to translate the time to your language. As @samhtm mentioned on the 2nd bullet point, you have to add a time as well.

**Comment by Vuong26** [comment]
help i got same issue

**Comment by Vuong26** [comment]
how to i change the time zone can u guys make a ex

**Comment by JorisvD01** [comment]
> how to i change the time zone can u guys make a ex

This is the wrong place to ask for something like this. If you got the same issue, you can get around it by using a datetime with the time, instead of only the date as the example by @samhtm shows above

**Comment by Vuong26** [comment]
> We've changed the API used for countdown, from Date to LocalDateTime to allow you to set the time zone (e.g. UTC+3) and the local to translate the time to your language. As [@samhtm](https://github.com/samhtm) mentioned on the 2nd bullet point, you have to add a time as well.

is there anyway to add utc+7 to this i only get random time
